# @package _global_

args:
  study_name: 3DR-profile1-${args.accelerator}${args.precision}-alpha_${run_config.parameters.preproc-basic_preproc-alpha}
  dry_run: False
  overwrite: False
  num_iters: 1
  max_epochs: 150
  accelerator: gpu
  precision: 32
  mode: run

ds:
  preproc_pipeline: null

pl:
  callbacks: null
  trainer:
    max_epochs: ${args.max_epochs}

run_config:
  parameters:
    preproc-basic_preproc-alpha: -1.0
    learning_rate: 0.0095
    optimizer: adam
    adam-beta1: 0.915
    adam-beta2: 0.902

    scheduler: borzelai-borwein
    bb-max_lr: 1e-1
    bb-min_lr: 1e-8
    bb-steps: 1
    bb-beta: 1e-2
    bb-weight_decay: 0.0

    model-loss: mds
    model-reg_Y_name: null
    model-reg_P_dist_name: null