# @package _global_

args:
  study_name: 3DR-profile1-${args.accelerator}${args.precision}-alpha_${run_config.parameters.preproc-basic_preproc-alpha}
  dry_run: False
  overwrite: False
  optimize: True
  num_trials: 1
  num_iters: 1
  max_epochs: 500
  accelerator: cpu
  precision: 64
  mode: run

ds:
  name: ??? #? add ds as an argument
  preproc_pipeline: null

pl:
  callbacks: null
  save_model: True
  save_model_path: outputs/profile1_cpu
  trainer:
    max_epochs: ${args.max_epochs}

run_config:
  parameters:
    preproc-basic_preproc-alpha: -1.0

    learning_rate: 0.0095  
    optimizer: sgd
    sgd-momentum: 0.99
    sgd-weight_decay: 0.05

    scheduler: null

    model-loss: mse
    model-reg_Y_name: null
    model-reg_P_dist_name: null