# @package _global_

args:
  study_name: 3DR-profile3-${args.accelerator}${args.precision}-alpha_${run_config.parameters.preproc-basic_preproc-alpha}
  dry_run: False
  overwrite: False
  optimize: True
  num_trials: 1
  num_iters: 1
  max_epochs: 150
  accelerator: cpu
  precision: 64
  mode: run

ds:
  preproc_pipeline: null

pl:
  callbacks: null
<<<<<<< HEAD
=======
  save_model: True
  save_model_path: outputs/profile3_cpu
  parameters:
    preproc-basic_preproc-alpha: -1.0
    learning_rate: 0.0095
    optimizer: adam
    adam-beta1: 0.915
    adam-beta2: 0.902

    scheduler: borzelai-borwein
    bb-max_lr: 1e-1
    bb-min_lr: 1e-8
    bb-steps: 1
    bb-beta: 1e-2
    bb-weight_decay: 0.0

    model-loss: mse
    model-reg_Y_name: null
    model-reg_P_dist_name: null